name: zSpawner
author: Maxlego08
main: fr.maxlego08.zspawner.ZSpawnerPlugin
version: PRE-3.0.1.7
api-version: 1.13
softdepend: [Essentials, Factions, LegacyFaction, PlaceholderAPI, SuperiorSkyblock2, MassiveCore, Guilds, FactionsX]
commands: